# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Poy Chang's Blog
subtitle: ''
description: ''
keywords:
author: Poy Chang
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.poychang.net
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# ==============================================================================
# Theme Settings
# ==============================================================================
theme_config:
  ##############################################################################
  # Content
  ##############################################################################
  projects_url: https://github.com/poychang/blog.poychang.net
  direction: ltr
  # Configure the navigation menu.
  # A pair 'Key: url' will result in a link to 'url' with the name 'Key' in the
  # navigation menu. Optionally, you can add translations for the 'Key' in
  # languages/*.yml
  nav:
    home: /
    about: /about/
    articles: /archives/
    projects: https://github.com/poychang


  # Links to your social media accounts.
  # The 'icon' keys should correspond to Fontawesome icon names
  # (see https://fontawesome.com/icons?d=gallery&s=brands);
  # only 'mail' is an exception.
  # You can optionally add a 'label' key to set the title attribute on the link. 
  # 'icon' value will be used as title when 'label' is missing.
  social_links:
    -
      icon: github
      link: https://github.com/poychang
    -
      icon: facebook
      link: https://www.facebook.com/poychang.tech
    -
      icon: LinkedIn
      label: LinkedIn
      link: https://www.linkedin.com/in/poychang
    -
      icon: mail
      link: mailto:poypost@gmail.com

  # Customize the overview with displaying a tagcloud on the index page.
  # Options: https://hexo.io/docs/helpers.html#tagcloud
  tags_overview: false

  # Customize the overview with the most recent blog posts on the index page.
  # Options:
  #   - show_all_posts: whether to show all available posts.
  #   - post_count: whether to show only the x most recent posts.
  #   - sort_updated: sort posts by last modification date instead of creation date.
  posts_overview:
    show_all_posts: false
    post_count: 10
    sort_updated: false

  # Customize the archive view.
  # Options:
  #   - sort_updated: sort posts by last modification date instead of creation date.
  # Note: this does not work together with pagination, since the pagination
  # plugin will sort pages by date of creation.
  archive:
    sort_updated: false

  # Customize the article view.
  # Options:
  #   - show_updated: show the last modification date.
  post:
    show_updated: false

  # Customize the copyright years
  # Note: if start_year/end_year not provided, will use current year.
  copyright:
    start_year: 2014
    end_year:

  # Customize the 404 page
  # Options:
  #   - enabled: whether to enable the 404 page (404.html).
  error_404:
    enabled: true
    title: "404 Page Not Found"
    description: "The page you are looking for might have been removed, had its name changed, or is temporarily unavailable."


  ##############################################################################
  # Look and Feel
  ##############################################################################

  # Customize the logo (i.e., the cactus) in the header.
  # Options:
  #   - enabled: whether to show (true) or hide (false) the logo.
  #   - width: width of the logo in pixel units
  #   - height: height of the logo in pixel units
  #   - url: where the logo can be found
  #   - gravatar: whether to use your Gravatar as the logo
  #   - grayout: whether to enable a hover effect on the logo
  logo:
    enabled: true
    width: 50
    height: 50
    url: /images/logo.png
    gravatar: false
    grayout: true

  # Customize the favicons.
  # Cactus supports a limited set of the three most important icons:
  #   - desktop: The classic favion.ico file.
  #   - android: A 192x192 PNG file.
  #   - apple:  A 180x180 PNG file.
  # These can be generated with http://realfavicongenerator.net/
  # Options:
  #   - url: where the icon can be found
  #   - gravatar: whether to create a favicon from your Gravatar
  favicon:
    desktop:
      url: /images/favicon.ico
      gravatar: false
    android:
      url: /images/favicon-192x192.png
      gravatar: false
    apple:
      url: /images/apple-touch-icon.png
      gravatar: false

  # The color scheme that should be used to highlight codeblocks.
  # See source/css/_highlight for a list of all available color schemes.
  # highlight: rainbow

  # Set the color scheme.
  # Available color schemes are 'dark', 'light', 'classic' and 'white'.
  # Alternatively, add your own custom color scheme to source/css/_colors.
  colorscheme: dark

  # Maximal width of the page in rem units.
  page_width: 60


  ##############################################################################
  # Miscellaneous
  ##############################################################################

  # Enable or disable the RSS feed.
  rss: false

  # Turn your web pages into graph objects (see http://ogp.me).
  open_graph:
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:


  ##############################################################################
  # Plugins
  ##############################################################################

  # Enable MathJax support for Latex
  mathjax:
    enabled: false

  # Fill in your Disqus Comments Shortname to enable Disqus comments.
  disqus:
    enabled: false
    shortname: cactus-1

  # Fill in your Utterances data to enable Utterances comments
  utterances:
    enabled: false
    repo: owner/githubrepo
    issue_term: pathname
    label: Comment
    theme: github-dark

  # Fill in your Google Analytics tracking ID to enable Google Analytics.
  google_analytics:
    enabled: true
    id: G-7ZF14W4E3R

  # Fill in your Baidu Analytics tracking ID to enable Baidu Analytics.
  baidu_analytics:
    enabled: false
    id: 2e6da3c375c8a87f5b664cea6d4cb29c

  # Fill in your Cloudflare Analytics tracking ID to enable Cloudflare Analytics.
  cloudflare_analytics:
    enabled: false
    id: 0dabb6e21848405483a237e6a7b6ed04

  # Fill in your Umami Analytics tracking ID to enable Umami Analytics.
  umami_analytics:
    enabled: false
    id: e77e68be-f6e4-4br3-9365-2b76b57cd571
    host: https://analytics.domain.com
    script_name: umami.js

  # Fill in you Gravatar email or hash if you want to use your gravatar as the
  # logo and/or favicons of you website.
  # To generate hash: `$ echo -n "name@email.com" | md5`.
  gravatar:
    email: poypost@gmail.com
    hash: c525d15ee116aca696f7af9a926e1788

  # loads libraries and styles from CDN instead or relying on local files
  cdn:
    enable: true
    jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
    clipboard: https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.7/clipboard.min.js
    font_awesome: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
    justified_gallery_css: https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.8.1/css/justifiedGallery.min.css
    justified_gallery_js: https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.8.1/js/jquery.justifiedGallery.min.js
